//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Shared__Layout_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Shared__Layout_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsPortal.Resources.Views.Shared._Layout.ru", typeof(Views_Shared__Layout_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админка.
        /// </summary>
        internal static string AdminPanelLink {
            get {
                return ResourceManager.GetString("AdminPanelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все новости.
        /// </summary>
        internal static string AllNewsLink {
            get {
                return ResourceManager.GetString("AllNewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние.
        /// </summary>
        internal static string LatestLink {
            get {
                return ResourceManager.GetString("LatestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string LogoutLink {
            get {
                return ResourceManager.GetString("LogoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новостной портал.
        /// </summary>
        internal static string NewsPortalTitle {
            get {
                return ResourceManager.GetString("NewsPortalTitle", resourceCulture);
            }
        }
    }
}
